#source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"
use_frameworks! 
target 'Promote' do
pod "RealmSwift"
pod "RxSwift"
pod "RxCocoa"
pod "Cartography"
pod "Alamofire"
pod "PKHUD"
pod "SnapKit"
end

