source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"
use_frameworks!  ## cocoapods 从0.38之后的版本开始，支持swift 了，当你在安装pods的时候，添加下面这句话就可以了
## 1.1.0.beta.1(目前cocopods版本)
target 'Promote' do
pod "RxSwift"
pod "RxCocoa"
pod "Cartography" # swift版的约束
pod "Alamofire"
pod "PKHUD"
#pod "NSObject+Rx"
end

